In [1]:
import numpy as np

In [2]:
############## ACTIVATION FUNCTIONS ##############################

def sigmoid(q):
    return(1/(1+np.exp(-q)))

def sigmoid_prime(q):
    return(sigmoid(q)*(1-sigmoid(q)))

def max_act(q):
    return(max(0, q))

def max_act_prime(q):
    if q > 0:
        return(1)
    else:
        return(0)

In [26]:
class Network:
    
    def __init__(self, W_list, input_matrix, act_list, y):
        self.X = input_matrix
        self.W_list = W_list
        self.y = y
        self.act_list = act_list
        self.delta_list = []
        
    def forward_pass(self):
        #act_values = np.zeros(act_list.shape)
        self.act_values = []
        self.sum_values = []
        
        for layer in range(len(self.act_list)): 
            if layer == 0:                # начинаем со второго слоя
                sum_fun = self.W_list[0].dot(self.X)
                act_fun = self.activate(sum_fun, self.act_list[layer])
                self.act_values.append(act_fun)
                self.sum_values.append(sum_fun)
            else:
                sum_fun = self.W_list[layer].dot(self.act_values[layer-1])
                act_fun = self.activate(sum_fun, self.act_list[layer])
                self.act_values.append(act_fun)
                self.sum_values.append(sum_fun)
        nabla_J = (self.act_values[-1] - self.y)/self.X.shape[1]
        self.delta_L = nabla_J*self.prime(self.act_list[layer],sum_fun)
        self.delta_list.append(self.delta_L)
        print("Вектор X:", self.X)
        print("Список автиваций:", self.act_values)
        print('Результат сложения')
        print()
        print(self.act_values)
        return(self.delta_L)
                
    def activate(self, summ, act_layer):
        act_res = np.zeros((len(act_layer),1))
        for i in range(len(act_layer)):  
            if act_layer[i] == 'max':
                act_res[i] = max_act(summ[i])
            elif act_layer[i] == 'sigm':
                act_res[i] = sigmoid(summ[i])
        return(act_res)
    
    def backprop(self):
        for layer in range(len(W_list)-1):
            curr_layer = len(W_list)-layer-1
            print('all_sum_values', self.sum_values)
            delta_l = self.W_list[curr_layer].T.dot(self.delta_list[layer])*self.prime(act_list[curr_layer-1],self.sum_values[curr_layer-1])
            self.delta_list.append(delta_l)
        return(list(reversed(self.delta_list)))
    
    
    def delta_W(self):
        dJ_dW = self.W_list
    # нужно добавить входы в act_values
        self.act_values.insert(0, self.X)
        for i in range(len(dJ_dW)):
            dJ_dW[i] = list(reversed(self.delta_list))[i].dot(self.act_values[i].T) 
            # первый элемент delta_list- список ошибок второго слоя
            #первый элемент act_values - список активаций первого слоя
        return dJ_dW
    

   
    def prime(self, act_layer, sum_layer):

        def find_prime(zipped_act_sum):
            act_neuron, sum_neuron = zipped_act_sum[0], zipped_act_sum[1]
            if act_neuron == 'max':
                return max_act_prime(sum_neuron)
            else:
                print('sig', type(sigmoid_prime(sum_neuron)),sigmoid_prime(sum_neuron))
                return sigmoid_prime(sum_neuron)
        
        print('sum-layer', sum_layer, sum_layer.shape)
        for each in map(find_prime, zip(act_layer, sum_layer)): print('checher',type(each))

        out = np.array(list(map(find_prime, zip(act_layer, sum_layer))))
    
        return(np.reshape(out, (len(act_layer),1)))
    
        

In [27]:
act_list = np.array([['max', 'sigm'], ['sigm']], dtype=object)
y = 1
W_list = [np.array([[0.7, 0.2, 0.7], [0.8, 0.3, 0.6]]), np.array([[0.2, 0.4]])]
input_matrix = np.array([[0.0, 1.0, 1.0]]).T




In [28]:
network = Network(W_list, input_matrix, act_list, y)
network.forward_pass()


sum-layer [[0.4643798]] (1, 1)
sig <class 'numpy.ndarray'> [0.23699199]
checher <class 'numpy.ndarray'>
sig <class 'numpy.ndarray'> [0.23699199]
Вектор X: [[0.]
 [1.]
 [1.]]
Список автиваций: [array([[0.9      ],
       [0.7109495]]), array([[0.61405267]])]
Результат сложения

[array([[0.9      ],
       [0.7109495]]), array([[0.61405267]])]


array([[-0.09146642]])

In [29]:
network.backprop()

all_sum_values [array([[0.9],
       [0.9]]), array([[0.4643798]])]
sum-layer [[0.9]
 [0.9]] (2, 1)
checher <class 'int'>
sig <class 'numpy.ndarray'> [0.20550031]
checher <class 'numpy.ndarray'>
sig <class 'numpy.ndarray'> [0.20550031]


[array([[-0.01829328],
        [-0.00751855]]),
 array([[-0.09146642]])]

In [8]:
network.delta_W()

[array([[-0.        , -0.01829328, -0.01829328],
        [-0.        , -0.00751855, -0.00751855]]),
 array([[-0.08231978, -0.06502801]])]

In [69]:
act_list[0]

['max', 'sigm']

In [8]:
a_copy = act_list.copy()
for in range(len(a_copy)

SyntaxError: invalid syntax (<ipython-input-8-d9320e1e57a8>, line 2)

In [ ]:
act_values = np.zeros(act_list.shape)

In [ ]:
act_values

In [ ]:
for i in range(3):
    print('@')

In [ ]:
len(W_list)

In [54]:
numbers = [4, 2, 3]

In [57]:
L = [lambda x: x**2, lambda x: x**3, lambda x: x]

In [60]:
m_numbers = []
for number, f in zip(numbers, L):
    m_numbers.append(f(number))

In [61]:
m_numbers

[16, 8, 3]

In [10]:
active_prime = []
active_names = ['sigm', 'max']
for name in active_names:
    if name == 'sigm':
        active_prime.append(lambda x: sigmoid(x))
    else:
        active_prime.append(lambda x: max_act(x))

In [15]:
test = [1, 2]
active_values = []
for a, sample in zip(active_prime, test):
    active_values.append(a(sample))

In [16]:
active_values

[0.7310585786300049, 2]

In [49]:
act_layer = ['sigm', 'max']
sum_layer = [1, 2]
```
def prime(act_layer, sum_layer):

    def find_prime(zipped_act_sum):
        act_neuron, sum_neuron = zipped_act_sum[0], zipped_act_sum[1]
        if act_neuron == 'max':
            return max_act(sum_neuron)
        else:
            return sigmoid_prime(sum_neuron)
        
    out = np.array(list(map(find_prime, zip(act_layer, sum_layer))))
    
    return(np.reshape(out, (len(act_layer),1)))
```


In [52]:
act_layer = ['sigm', 'sigm']
sum_layer = [1, 2]

find_prime(act_layer, sum_layer)

array([[0.19661193],
       [0.10499359]])

In [37]:
list(zip(act_layer, sum_layer))[0][0]

'sigm'

In [39]:
mapped

[0.19661193324148185, 2]